### ISSUE TITLE
UpgradeHandler dojo workshop

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/dojo#1]
**Acceptance criteria**
L1 seniors approves the dojo workshop module

**Tasks**
- [ ] Create workshop module
- [ ] Present for peer review
- [ ] Publish to dojo and inform L2 dev community

**Comment by ZaradarBH** [comment]
Closing, we will handle this in the context of the new dojo workshop and migrate over the presentation @Ragepie put togetheer :)
