### ISSUE TITLE
Cosmovisor dojo workshop

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/dojo#2]
**Acceptance criteria**
L1 seniors approves the dojo workshop module

**Tasks**
- [ ] Create workshop module
- [ ] Present for peer review
- [ ] Publish to dojo and inform L2 dev community

**Comment by elzorrorebelde** [comment]
FYI: I'm making some notes here for use later on https://shackra.notion.site/Notes-on-Cosmovisor-98687f6bc79e45a68344b4a0bc126dfd

**Comment by ZaradarBH** [comment]
Closing this issue. We will handle Cosmovisor in the Cosmos-SDK expert path. Your welcome to pitch in @shackra
